name: Build project
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build project
        shell: powershell
        run: |
          # 1. Load the ESP-IDF environment tools from your user folder
          . $HOME\.espressif\eim_gui\..\..\esp\esp-idf\export.ps1
          
          # 2. Move to your project folder
          cd "E:\robotics projects\esp-drone-master (1)\esp-drone-master"
          
          # 3. Compile the project
          idf.py build
