name: Build project
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build project
        shell: powershell
        run: |
          cd "E:\robotics projects\esp-drone-master (1)\esp-drone-master"
          idf.py build
